# Generated by Django 3.0.4 on 2020-03-10 20:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, default='', editable=False, max_length=100)),
                ('name', models.CharField(max_length=128)),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('UAH', 'UAH'), ('USD', 'USD')], default='UAH', editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_accounts.account_set+', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
                ('api_account_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='CounterpartyAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
                ('api_account_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('interest_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('principal_payment_method', models.CharField(choices=[('equal_payment', 'Рівними частинами'), ('equal_instalment', 'Основна сума рівними частинами'), ('one_time', 'В кінці строку'), ('custom_scheme', 'Кастомізована схема')], default='one_time', max_length=40)),
                ('interest_payment_method', models.CharField(choices=[('monthly_payment', 'Щомісячна виплата'), ('monthly_capital', 'Щомісячне додавання до основної суми'), ('one_time', 'В кінці строку')], default='monthly_payment', max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account', models.Model),
        ),
        migrations.CreateModel(
            name='IncomeBalance',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
                ('api_account_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('interest_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('principal_payment_method', models.CharField(choices=[('equal_payment', 'Рівними частинами'), ('equal_instalment', 'Основна сума рівними частинами'), ('one_time', 'В кінці строку'), ('custom_scheme', 'Кастомізована схема')], default='one_time', max_length=40)),
                ('interest_payment_method', models.CharField(choices=[('monthly_payment', 'Щомісячна виплата'), ('monthly_capital', 'Щомісячне додавання до основної суми'), ('one_time', 'В кінці строку')], default='monthly_payment', max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account', models.Model),
        ),
        migrations.CreateModel(
            name='SpendingBalance',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account',),
        ),
    ]
