# Generated by Django 2.2.8 on 2020-01-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomebalance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spendingbalance',
            options={},
        ),
    ]
