# Generated by Django 2.2.8 on 2020-01-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_auto_20200105_1303'),
        ('accounts', '0002_auto_20200105_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='counterparties.Counterparty')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account',),
        ),
    ]
