# Generated by Django 3.0.2 on 2020-01-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_counterpartyaccount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_user_name',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='account_unique_user_name'),
        ),
    ]
