# Generated by Django 3.0.2 on 2020-02-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200126_1607'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_user_account_type',
        ),
        migrations.RemoveConstraint(
            model_name='account',
            name='positive_balance_debit',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_type',
            new_name='item_type',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(
                condition=models.Q(item_type__in=['spendingbalance', 'incomebalance']),
                fields=('user', 'item_type'), name='unique_user_item_type'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0),
                                                             models.Q(_negated=True,
                                                                      item_type='cashaccount'),
                                                             _connector='OR'),
                                              name='positive_balance_debit'),
        ),
    ]
