# Generated by Django 3.0.4 on 2020-03-08 09:32

import apps.accounts.models
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0005_bank_api_class'),
        ('accounts', '0005_auto_20200222_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBankAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
                ('api_account_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='DebitBankAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
                ('api_account_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account',),
        ),
        migrations.RemoveConstraint(
            model_name='account',
            name='positive_balance_debit',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('UAH', 'UAH'), ('USD', 'USD')], default='UAH', editable=False, max_length=3),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0), models.Q(_negated=True, item_type__in=['cashaccount', 'debitbankaccount', 'deposit']), _connector='OR'), name='positive_balance_debit'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('debitbankaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.DebitBankAccount')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.accounts.models.TermAgreementMixin, 'accounts.debitbankaccount'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('creditbankaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.CreditBankAccount')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.accounts.models.TermAgreementMixin, 'accounts.creditbankaccount'),
        ),
        migrations.AddField(
            model_name='debitbankaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counterparties.Bank'),
        ),
        migrations.AddField(
            model_name='creditbankaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counterparties.Bank'),
        ),
    ]
