# Generated by Django 3.0.4 on 2020-03-08 10:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0005_bank_api_class'),
        ('accounts', '0005_auto_20200222_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBankAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
                ('api_account_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='DebitBankAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Account')),
                ('api_account_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account',),
        ),
        migrations.RemoveConstraint(
            model_name='account',
            name='positive_balance_debit',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('UAH', 'UAH'), ('USD', 'USD')], default='UAH', editable=False, max_length=3),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0), models.Q(_negated=True, item_type__in=['cashaccount', 'debitbankaccount', 'deposit']), _connector='OR'), name='positive_balance_debit'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('debitbankaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.DebitBankAccount')),
                ('interest_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('principal_payment_method', models.CharField(choices=[('equal_payment', 'Рівними частинами'), ('equal_instalment', 'Основна сума рівними частинами'), ('one_time', 'В кінці строку'), ('custom_scheme', 'Кастомізована схема')], default='one_time', max_length=40)),
                ('interest_payment_method', models.CharField(choices=[('monthly_payment', 'Щомісячна виплата'), ('monthly_capital', 'Щомісячне додавання до основної суми'), ('one_time', 'В кінці строку')], default='monthly_payment', max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.debitbankaccount', models.Model),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('creditbankaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.CreditBankAccount')),
                ('interest_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('principal_payment_method', models.CharField(choices=[('equal_payment', 'Рівними частинами'), ('equal_instalment', 'Основна сума рівними частинами'), ('one_time', 'В кінці строку'), ('custom_scheme', 'Кастомізована схема')], default='one_time', max_length=40)),
                ('interest_payment_method', models.CharField(choices=[('monthly_payment', 'Щомісячна виплата'), ('monthly_capital', 'Щомісячне додавання до основної суми'), ('one_time', 'В кінці строку')], default='monthly_payment', max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.creditbankaccount', models.Model),
        ),
        migrations.AddField(
            model_name='debitbankaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counterparties.Bank'),
        ),
        migrations.AddField(
            model_name='creditbankaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counterparties.Bank'),
        ),
    ]
