# Generated by Django 3.0.4 on 2020-03-08 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200308_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='interest_payment_method',
            field=models.CharField(choices=[('monthly_payment', 'Щомісячна виплата'), ('monthly_capital', 'Щомісячне додавання до основної суми'), ('one_time', 'В кінці строку')], default='monthly_payment', max_length=40),
        ),
        migrations.AddField(
            model_name='deposit',
            name='interest_rate',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='principal_payment_method',
            field=models.CharField(choices=[('equal_payment', 'Рівними частинами'), ('equal_instalment', 'Основна сума рівними частинами'), ('one_time', 'В кінці строку'), ('custom_scheme', 'Кастомізована схема')], default='one_time', max_length=40),
        ),
        migrations.AddField(
            model_name='deposit',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_payment_method',
            field=models.CharField(choices=[('monthly_payment', 'Щомісячна виплата'), ('monthly_capital', 'Щомісячне додавання до основної суми'), ('one_time', 'В кінці строку')], default='monthly_payment', max_length=40),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='principal_payment_method',
            field=models.CharField(choices=[('equal_payment', 'Рівними частинами'), ('equal_instalment', 'Основна сума рівними частинами'), ('one_time', 'В кінці строку'), ('custom_scheme', 'Кастомізована схема')], default='one_time', max_length=40),
        ),
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
