# Generated by Django 3.0.4 on 2020-03-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200308_1234'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_user_item_type',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(item_type__in=['spendingbalance', 'incomebalance']), fields=('user', 'item_type', 'balance_currency'), name='unique_user_item_type'),
        ),
    ]
