# Generated by Django 3.0.4 on 2020-03-10 20:38

import apps.common.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('accounts', '0002_auto_20200310_2238'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, default='', editable=False, max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('UAH', 'UAH'), ('USD', 'USD')], default='UAH', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[apps.common.validators.MinMoneyValidator(0.01)])),
                ('description', models.TextField(blank=True, default='')),
                ('is_completed', models.BooleanField(default=True)),
                ('account_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_from', to='accounts.Account')),
                ('account_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_to', to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'transaction categories',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.Transaction')),
            ],
            options={
                'abstract': False,
            },
            bases=('transactions.transaction',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.TransactionCategory'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_transactions.transaction_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.Transaction')),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='counterparties.Counterparty')),
            ],
            options={
                'abstract': False,
            },
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.Transaction')),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spendings', to='counterparties.Counterparty')),
            ],
            options={
                'abstract': False,
            },
            bases=('transactions.transaction',),
        ),
    ]
