# Generated by Django 3.0.4 on 2020-03-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='api_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
