# Generated by Django 3.0.2 on 2020-01-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200105_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncategory',
            name='code',
        ),
    ]
