# Generated by Django 2.2.8 on 2020-01-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, default='', editable=False, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_counterparties.counterparty_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('counterparty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='counterparties.Counterparty')),
            ],
            options={
                'abstract': False,
            },
            bases=('counterparties.counterparty',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('counterparty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='counterparties.Counterparty')),
            ],
            options={
                'abstract': False,
            },
            bases=('counterparties.counterparty',),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('counterparty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='counterparties.Counterparty')),
            ],
            options={
                'abstract': False,
            },
            bases=('counterparties.counterparty',),
        ),
    ]
