# Generated by Django 3.0.4 on 2020-03-10 20:38

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, default='', editable=False, max_length=100)),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=200)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_counterparties.counterparty_set+', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'counterparties',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('counterparty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='counterparties.Counterparty')),
                ('api_class', models.CharField(blank=True, choices=[('MonobankAPI', 'Monobank API')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('counterparties.counterparty',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('counterparty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='counterparties.Counterparty')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
            bases=('counterparties.counterparty',),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('counterparty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='counterparties.Counterparty')),
            ],
            options={
                'abstract': False,
            },
            bases=('counterparties.counterparty',),
        ),
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'item_type'), name='counterparty_unique_user_name'),
        ),
    ]
