# Generated by Django 2.2.8 on 2020-01-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterparty',
            options={'verbose_name_plural': 'counterparties'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
    ]
