# Generated by Django 3.0.2 on 2020-01-26 14:07

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counterparties', '0002_auto_20200105_1303'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='counterparty_unique_user_name'),
        ),
    ]
