# Generated by Django 3.0.4 on 2020-03-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0004_auto_20200222_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='api_class',
            field=models.CharField(blank=True, choices=[('MonobankAPI', 'Monobank API')], max_length=50, null=True),
        ),
    ]
