# Generated by Django 3.0.4 on 2020-03-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0005_bank_api_class'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='counterparty',
            name='counterparty_unique_user_name',
        ),
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'item_type'), name='counterparty_unique_user_name'),
        ),
    ]
